//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineAssessment.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Btn_No {
            get {
                return ResourceManager.GetString("Btn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start now.
        /// </summary>
        public static string Btn_StartNow {
            get {
                return ResourceManager.GetString("Btn_StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Btn_Yes {
            get {
                return ResourceManager.GetString("Btn_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should call 811 for further assessment by a health professional..
        /// </summary>
        public static string Call811_P1 {
            get {
                return ResourceManager.GetString("Call811_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must also self-isolate for 14 days and continue to monitor your health..
        /// </summary>
        public static string Call811_P2 {
            get {
                return ResourceManager.GetString("Call811_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you travelled recently, this means 14 days from the day you returned to Canada..
        /// </summary>
        public static string Call811_P3 {
            get {
                return ResourceManager.GetString("Call811_P3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you had close contact with someone with confirmed OnlineAssessment or someone with symptoms who has recently returned to Canada, this means 14 days from the day you had contact..
        /// </summary>
        public static string Call811_P4 {
            get {
                return ResourceManager.GetString("Call811_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re experiencing higher than normal call volumes. It&apos;ll take longer than usual to respond to your call. We&apos;re working hard to respond to all calls as quickly as possible. Thank you for your patience..
        /// </summary>
        public static string Call811_P5 {
            get {
                return ResourceManager.GetString("Call811_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should call 811.
        /// </summary>
        public static string Call811_PageTitle {
            get {
                return ResourceManager.GetString("Call811_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canada.ca/coronavirus.
        /// </summary>
        public static string CanadaInfoLink {
            get {
                return ResourceManager.GetString("CanadaInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.canada.ca/en/public-health/services/diseases/coronavirus-disease-covid-19.htm.
        /// </summary>
        public static string CanadInfo_href {
            get {
                return ResourceManager.GetString("CanadInfo_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been in close contact (within 2 metres) with someone with a confirmed case of COVID-19?.
        /// </summary>
        public static string ContactWithConfirmedCase_H2 {
            get {
                return ResourceManager.GetString("ContactWithConfirmedCase_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with people who have confirmed COVID-19.
        /// </summary>
        public static string ContactWithConfirmedCase_PageTitle {
            get {
                return ResourceManager.GetString("ContactWithConfirmedCase_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been in close contact (within 2 metres) with someone who has returned from another country in the past 14 days and who has a fever higher than 38C, a new cough or a cough that’s getting worse?.
        /// </summary>
        public static string ContactWithSymptoms_H2 {
            get {
                return ResourceManager.GetString("ContactWithSymptoms_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with people with symptoms.
        /// </summary>
        public static string ContactWithSymptoms_PageTitle {
            get {
                return ResourceManager.GetString("ContactWithSymptoms_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this screening tool to find out if you should call 811 about COVID-19..
        /// </summary>
        public static string Index_H2 {
            get {
                return ResourceManager.GetString("Index_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only certain people need to call about COVID-19. Don’t call if you don’t need to..
        /// </summary>
        public static string Index_P1 {
            get {
                return ResourceManager.GetString("Index_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer the questions on each page of this tool to find out if you should call..
        /// </summary>
        public static string Index_P2 {
            get {
                return ResourceManager.GetString("Index_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have concerns about another health issue, you can still call 811 to speak to a health professional. We’re experiencing higher than normal call volumes, so it’ll take longer than usual to respond to your call. We’re working hard to respond to all calls as quickly as we can. Thank you for your patience..
        /// </summary>
        public static string Index_P3 {
            get {
                return ResourceManager.GetString("Index_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When to call 811 about COVID-19.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on COVID-19, including how to self-isolate, visit.
        /// </summary>
        public static string Info811_1 {
            get {
                return ResourceManager.GetString("Info811_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Or call the Government of Canada’s toll-free information line at.
        /// </summary>
        public static string Info811_2 {
            get {
                return ResourceManager.GetString("Info811_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_English {
            get {
                return ResourceManager.GetString("Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Lang_French {
            get {
                return ResourceManager.GetString("Lang_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to start.
        /// </summary>
        public static string Link_BackToStart {
            get {
                return ResourceManager.GetString("Link_BackToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string MetaLang {
            get {
                return ResourceManager.GetString("MetaLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must self-isolate..
        /// </summary>
        public static string NoCallRightNow_H2 {
            get {
                return ResourceManager.GetString("NoCallRightNow_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Department of Health and Wellness requires you to self-isolate for 14 days..
        /// </summary>
        public static string NoCallRightNow_P1 {
            get {
                return ResourceManager.GetString("NoCallRightNow_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you travelled recently, this means 14 days from the day you returned to Canada..
        /// </summary>
        public static string NoCallRightNow_P2 {
            get {
                return ResourceManager.GetString("NoCallRightNow_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you had close contact with someone with confirmed COVID-19 or someone with symptoms who has recently returned to Canada, this means 14 days from the day you had contact..
        /// </summary>
        public static string NoCallRightNow_P3 {
            get {
                return ResourceManager.GetString("NoCallRightNow_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should continue to monitor your health. If anything changes, you can use this tool to re-assess..
        /// </summary>
        public static string NoCallRightNow_P4 {
            get {
                return ResourceManager.GetString("NoCallRightNow_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you develop a fever higher than 38C or a new cough (or one that gets worse) within 14 days then you should call 811 for further assessment by a health professional..
        /// </summary>
        public static string NoCallRightNow_P5 {
            get {
                return ResourceManager.GetString("NoCallRightNow_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to call 811 right now.
        /// </summary>
        public static string NoCallRightNow_PageTitle {
            get {
                return ResourceManager.GetString("NoCallRightNow_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the information you provided, there’s no reason to call 811 for an assessment right now..
        /// </summary>
        public static string NoCallTo811_P1 {
            get {
                return ResourceManager.GetString("NoCallTo811_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If anything changes you can use this tool to re-assess..
        /// </summary>
        public static string NoCallTo811_P2 {
            get {
                return ResourceManager.GetString("NoCallTo811_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on COVID-19, visit.
        /// </summary>
        public static string NoCallTo811_P3_1 {
            get {
                return ResourceManager.GetString("NoCallTo811_P3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Or call the Government of Canada’s toll-free information line at.
        /// </summary>
        public static string NoCallTo811_P3_2 {
            get {
                return ResourceManager.GetString("NoCallTo811_P3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have concerns about another health issue, you can still call 811 to speak to a health professional. We’re experiencing higher than normal call volumes, so it’ll take longer than usual to respond to your call..
        /// </summary>
        public static string NoCallTo811_P4 {
            get {
                return ResourceManager.GetString("NoCallTo811_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t need to call 811.
        /// </summary>
        public static string NoCallTo811_PageTitle {
            get {
                return ResourceManager.GetString("NoCallTo811_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ProvinceInfo_href {
            get {
                return ResourceManager.GetString("ProvinceInfo_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province coronavirus .
        /// </summary>
        public static string ProvinceInfo_Link {
            get {
                return ResourceManager.GetString("ProvinceInfo_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about your symptoms.
        /// </summary>
        public static string Symptoms_PageTitle {
            get {
                return ResourceManager.GetString("Symptoms_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a fever higher than 38C, a new cough or a cough that’s getting worse?.
        /// </summary>
        public static string SymptomsWithoutTravel_H2 {
            get {
                return ResourceManager.GetString("SymptomsWithoutTravel_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a fever higher than 38C, a new cough or a cough that’s getting worse?.
        /// </summary>
        public static string SymptomsWithTravel_H2 {
            get {
                return ResourceManager.GetString("SymptomsWithTravel_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you returned to Canada from another country within the past 14 days?.
        /// </summary>
        public static string TravelInfo_H2 {
            get {
                return ResourceManager.GetString("TravelInfo_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about your recent travel.
        /// </summary>
        public static string TravelInfo_PageTitle {
            get {
                return ResourceManager.GetString("TravelInfo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or .
        /// </summary>
        public static string Txt_Or {
            get {
                return ResourceManager.GetString("Txt_Or", resourceCulture);
            }
        }
    }
}
